/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.pim.view;

/**
 *
 * @author S-Developers
 */
public class Bill extends javax.swing.JPanel {

    /**
     * Creates new form Bill
     */
    public Bill() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtLastName = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        txtTelephone = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        cbxTypeOfPayment = new javax.swing.JComboBox<>();
        txtTypeOfPayment = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        lblTotal = new javax.swing.JLabel();
        lblTelephoneClient = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        txtName = new javax.swing.JTextField();
        txtCI = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnOk = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lblArticles = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(970, 650));
        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(970, 650));
        jPanel1.setPreferredSize(new java.awt.Dimension(970, 650));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtLastName.setToolTipText("Enter Client's Last Name");
        txtLastName.setBorder(null);
        jPanel1.add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 40, 200, 30));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 70, 200, 30));

        txtTelephone.setToolTipText("Enter Client's Telephone");
        txtTelephone.setBorder(null);
        txtTelephone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelephoneActionPerformed(evt);
            }
        });
        jPanel1.add(txtTelephone, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 100, 200, 30));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 130, 200, 30));

        cbxTypeOfPayment.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbxTypeOfPayment.setToolTipText("Enter Type Of Payment Method");
        cbxTypeOfPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTypeOfPaymentActionPerformed(evt);
            }
        });
        jPanel1.add(cbxTypeOfPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 160, 150, -1));

        txtTypeOfPayment.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTypeOfPayment.setText("Type Of Payment:");
        jPanel1.add(txtTypeOfPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 160, -1, -1));

        txtTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTotal.setText("$");
        jPanel1.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 240, 150, -1));

        lblTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTotal.setText("Total:");
        jPanel1.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 240, 60, 30));

        lblTelephoneClient.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTelephoneClient.setText("Telephone:");
        jPanel1.add(lblTelephoneClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 110, -1, -1));

        lblLastName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblLastName.setText("Last Name:");
        jPanel1.add(lblLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, -1, -1));

        lblName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblName.setText("Name:");
        jPanel1.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, -1, -1));

        lblID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblID.setText("CI:");
        lblID.setToolTipText("");
        jPanel1.add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, -1, -1));

        txtEmail.setToolTipText("Enter Client's Email");
        txtEmail.setBorder(null);
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 200, 30));

        lblEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblEmail.setText("Email:");
        jPanel1.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 200, 30));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 200, 30));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 200, 30));

        txtName.setToolTipText("Enter Client's Name");
        txtName.setBorder(null);
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 200, 30));

        txtCI.setToolTipText("Enter Client's ID");
        txtCI.setBorder(null);
        jPanel1.add(txtCI, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 200, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/pqpqp.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 530));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "BRAND", "COLOR", "SIZE", "PRICE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setMinimumSize(new java.awt.Dimension(970, 650));
        jTable1.setPreferredSize(new java.awt.Dimension(970, 650));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 590, 180));

        btnOk.setText("Ok");
        jPanel1.add(btnOk, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 480, -1, -1));

        btnCancel.setText("Cancel");
        jPanel1.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 480, -1, -1));

        lblArticles.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblArticles.setText("Articles:");
        jPanel1.add(lblArticles, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, -1, -1));

        add(jPanel1, "card3");
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtTelephoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelephoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelephoneActionPerformed

    private void cbxTypeOfPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTypeOfPaymentActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cbxTypeOfPaymentActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOk;
    private javax.swing.JComboBox<String> cbxTypeOfPayment;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblArticles;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTelephoneClient;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTextField txtCI;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtTelephone;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JLabel txtTypeOfPayment;
    // End of variables declaration//GEN-END:variables
}
