/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.pim.view;

import com.sun.awt.AWTUtilities;

/**
 *
 * @author ismae
 */
public class FrmMainLogin extends javax.swing.JFrame {

    int x,y;
    /**
     * Creates new form main
     */
    public FrmMainLogin() {
        initComponents();
        AWTUtilities.setWindowOpaque(this, true);
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanelBackground = new javax.swing.JPanel();
        jUser = new javax.swing.JLabel();
        jUser1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jTxtUser = new javax.swing.JTextField();
        jbtnLoging = new javax.swing.JButton();
        lblClose = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        lblClose1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(102, 102, 255));
        setUndecorated(true);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        JPanelBackground.setBackground(new java.awt.Color(51, 51, 51));
        JPanelBackground.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        JPanelBackground.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                JPanelBackgroundMouseDragged(evt);
            }
        });
        JPanelBackground.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JPanelBackgroundMouseClicked(evt);
            }
        });
        JPanelBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jUser.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jUser.setForeground(new java.awt.Color(255, 255, 255));
        jUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jUser.setText("Password:");
        JPanelBackground.add(jUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 130, 40));

        jUser1.setBackground(new java.awt.Color(51, 51, 51));
        jUser1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jUser1.setForeground(new java.awt.Color(255, 255, 255));
        jUser1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jUser1.setText("User name:");
        JPanelBackground.add(jUser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 140, 40));

        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));
        JPanelBackground.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 320, 10));

        jSeparator2.setForeground(new java.awt.Color(102, 102, 102));
        JPanelBackground.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 320, 10));

        jTxtUser.setBackground(new java.awt.Color(51, 51, 51));
        jTxtUser.setForeground(new java.awt.Color(255, 255, 255));
        jTxtUser.setBorder(null);
        JPanelBackground.add(jTxtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 320, 40));

        jbtnLoging.setBackground(new java.awt.Color(255, 218, 51));
        jbtnLoging.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnLoging.setText("Login");
        jbtnLoging.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnLogingMouseClicked(evt);
            }
        });
        JPanelBackground.add(jbtnLoging, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 100, 40));

        lblClose.setBackground(new java.awt.Color(51, 51, 51));
        lblClose.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblClose.setForeground(new java.awt.Color(255, 255, 255));
        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.setText("_");
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
        });
        JPanelBackground.add(lblClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 30, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/pngegg.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(150, 150));
        JPanelBackground.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 160, 160));

        jPasswordField1.setBackground(new java.awt.Color(51, 51, 51));
        jPasswordField1.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField1.setBorder(null);
        JPanelBackground.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 212, 320, 40));

        lblClose1.setBackground(new java.awt.Color(51, 51, 51));
        lblClose1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblClose1.setForeground(new java.awt.Color(255, 255, 255));
        lblClose1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose1.setText("X");
        lblClose1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblClose1MouseClicked(evt);
            }
        });
        JPanelBackground.add(lblClose1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 30, 30));

        getContentPane().add(JPanelBackground);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JPanelBackgroundMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPanelBackgroundMouseDragged
        // TODO add your handling code here:
        this.setLocation(this.getLocation().x + evt.getX() - x,this.getLocation().y + evt.getY()- y);
        
    }//GEN-LAST:event_JPanelBackgroundMouseDragged

    private void JPanelBackgroundMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPanelBackgroundMouseClicked
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_JPanelBackgroundMouseClicked

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lblCloseMouseClicked

    private void jbtnLogingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnLogingMouseClicked
        // TODO add your handling code here:
        
        FrmMenuAdmin window = new FrmMenuAdmin();
        FrmUserMenu frmUser = new FrmUserMenu();
        if("Admin".equals(jTxtUser.getText()) && "root".equals(jPasswordField1.getText())){
            this.hide();
            window.show();
        }else{
            this.hide();
            frmUser.show();
        }
        
    }//GEN-LAST:event_jbtnLogingMouseClicked

    private void lblClose1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClose1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lblClose1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMainLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMainLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMainLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMainLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMainLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelBackground;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTxtUser;
    private javax.swing.JLabel jUser;
    private javax.swing.JLabel jUser1;
    private javax.swing.JButton jbtnLoging;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblClose1;
    // End of variables declaration//GEN-END:variables
}
