/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.pim.view;

/**
 *
 * @author lesly
 */
public class FrmSellProduct extends javax.swing.JPanel {

    /**
     * Creates new form FrmSellProduct
     */
    public FrmSellProduct() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblPim = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        btnsearch = new javax.swing.JButton();
        btnShop = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cmbColor2 = new javax.swing.JComboBox<>();
        cmbSize2 = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        cmbSize3 = new javax.swing.JComboBox<>();
        cmbColor3 = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        cmbSize4 = new javax.swing.JComboBox<>();
        cmbColor4 = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        cmbSize5 = new javax.swing.JComboBox<>();
        cmbColor5 = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        cmbSize6 = new javax.swing.JComboBox<>();
        cmbColor6 = new javax.swing.JComboBox<>();
        jLabel30 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        cmbSize7 = new javax.swing.JComboBox<>();
        cmbColor7 = new javax.swing.JComboBox<>();
        jLabel34 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(926, 640));
        setLayout(new java.awt.CardLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Iconpng2.png"))); // NOI18N
        jLabel1.setToolTipText("");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 117));

        lblPim.setFont(new java.awt.Font("Snap ITC", 3, 48)); // NOI18N
        lblPim.setForeground(new java.awt.Color(204, 0, 0));
        lblPim.setText("PIM");
        jPanel2.add(lblPim, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 150, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 380, 10));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/buscar.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, -1, -1));

        jTextField1.setBorder(null);
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 340, 40));

        btnsearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnsearch.setText("Search");
        btnsearch.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(btnsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 50, 60, 40));

        btnShop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/cart.png"))); // NOI18N
        jPanel2.add(btnShop, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 20, 70, 70));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setLabelFor(btnShop);
        jLabel5.setText("Shopping cart");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 90, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("ID: 747924 ");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Brand: ZARA");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 110, 20));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("ShoeType: Heeled");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, -1, -1));

        cmbColor2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbColor2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Color", "Red", "Pink", "Gold", "Rose Gold" }));
        jPanel2.add(cmbColor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 90, -1));

        cmbSize2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbSize2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Size", "34", "35", "36", "37", "38" }));
        jPanel2.add(cmbSize2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 90, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel17.setText("$45.00");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 70, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setText("Add to a car");
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 230, -1));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 10, 220));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/shoe2.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 110, 110));

        cmbSize3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbSize3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Size", "34", "35", "36", "37", "38" }));
        jPanel2.add(cmbSize3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 90, -1));

        cmbColor3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbColor3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Color", "Red", "Pink", "Gold", "Rose Gold" }));
        jPanel2.add(cmbColor3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, 90, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel18.setText("$80.00");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, 70, -1));

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton5.setText("Add to a car");
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, 230, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("ShoeType: Casual");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Brand: Lacoste");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 110, 20));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("ID: 849473 ");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, -1, -1));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, 10, 220));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/shoe3.png"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 130, 120, 140));

        cmbSize4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbSize4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Size", "34", "35", "36", "37", "38" }));
        jPanel2.add(cmbSize4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 260, 90, -1));

        cmbColor4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbColor4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Color", "Red", "Pink", "Gold", "Rose Gold" }));
        jPanel2.add(cmbColor4, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 260, 90, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel22.setText("$20.00");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 300, 70, -1));

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton6.setText("Add to a car");
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 330, 230, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setText("ShoeType: Scholar");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 220, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("Brand: Venus");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 180, 110, 20));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setText("ID: 937493 ");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 150, -1, -1));

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 140, 10, 220));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/shoes3.png"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 160, 110));

        cmbSize5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbSize5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Size", "34", "35", "36", "37", "38" }));
        jPanel2.add(cmbSize5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, 90, -1));

        cmbColor5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbColor5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Color", "Red", "Pink", "Gold", "Rose Gold" }));
        jPanel2.add(cmbColor5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 500, 90, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel26.setText("$96.00");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 540, 70, -1));

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton7.setText("Add to a car");
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 570, 230, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setText("ShoeType: Sport");
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 460, -1, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel28.setText("Brand: Nike");
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, 110, 20));

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel29.setText("ID: 638480");
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, -1, -1));

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, 10, 220));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/shoe4.png"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 110, 110));

        cmbSize6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbSize6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Size", "34", "35", "36", "37", "38" }));
        jPanel2.add(cmbSize6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 500, 90, -1));

        cmbColor6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbColor6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Color", "Red", "Pink", "Gold", "Rose Gold" }));
        jPanel2.add(cmbColor6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 500, 90, -1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel30.setText("$40.00");
        jPanel2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 540, 70, -1));

        jButton8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton8.setText("Add to a car");
        jPanel2.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 570, 230, -1));

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel31.setText("ShoeType: Sport");
        jPanel2.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 460, -1, -1));

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel32.setText("Brand: Bubble Gums");
        jPanel2.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 420, 130, 20));

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel33.setText("ID: 283494");
        jPanel2.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 390, -1, -1));

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 380, 10, 220));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/shoe5.png"))); // NOI18N
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 370, 120, 110));

        cmbSize7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbSize7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Size", "34", "35", "36", "37", "38" }));
        jPanel2.add(cmbSize7, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 500, 90, -1));

        cmbColor7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbColor7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Color", "Red", "Pink", "Gold", "Rose Gold" }));
        jPanel2.add(cmbColor7, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 500, 90, -1));

        jLabel34.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel34.setText("$70.00");
        jPanel2.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 540, 70, -1));

        jButton9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton9.setText("Add to a car");
        jPanel2.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 570, 230, -1));

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel35.setText("ShoeType: Boots");
        jPanel2.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 460, -1, -1));

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel36.setText("Brand: CAT");
        jPanel2.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 420, 110, 20));

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel37.setText("ID: 394739");
        jPanel2.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 390, -1, -1));

        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 380, 10, 220));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/shoe2.png"))); // NOI18N
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 130, 120));

        add(jPanel2, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnShop;
    private javax.swing.JButton btnsearch;
    private javax.swing.JComboBox<String> cmbColor2;
    private javax.swing.JComboBox<String> cmbColor3;
    private javax.swing.JComboBox<String> cmbColor4;
    private javax.swing.JComboBox<String> cmbColor5;
    private javax.swing.JComboBox<String> cmbColor6;
    private javax.swing.JComboBox<String> cmbColor7;
    private javax.swing.JComboBox<String> cmbSize2;
    private javax.swing.JComboBox<String> cmbSize3;
    private javax.swing.JComboBox<String> cmbSize4;
    private javax.swing.JComboBox<String> cmbSize5;
    private javax.swing.JComboBox<String> cmbSize6;
    private javax.swing.JComboBox<String> cmbSize7;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblPim;
    // End of variables declaration//GEN-END:variables
}
