/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.pim.view;

import ec.edu.espe.pim.controller.UserActivity;
import java.io.FileReader;
import java.io.FileWriter;
import javax.swing.JOptionPane;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;

/**
 *
 * @author S-Developers
 */
public class AddUser extends javax.swing.JPanel {

    /**
     * Creates new form AddUser
     */
    public AddUser() {
        initComponents();
        txtUser.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAddUser = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        lblPass = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        PswPass = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 102, 102));
        setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        setMinimumSize(new java.awt.Dimension(690, 190));
        setPreferredSize(new java.awt.Dimension(550, 450));
        setLayout(null);

        btnAddUser.setBackground(new java.awt.Color(51, 51, 255));
        btnAddUser.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnAddUser.setForeground(new java.awt.Color(255, 255, 255));
        btnAddUser.setText("Add new user");
        btnAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUserActionPerformed(evt);
            }
        });
        add(btnAddUser);
        btnAddUser.setBounds(170, 340, 200, 50);

        jSeparator1.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        add(jSeparator1);
        jSeparator1.setBounds(170, 290, 310, 20);

        jSeparator2.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        add(jSeparator2);
        jSeparator2.setBounds(180, 220, 300, 20);

        lblPass.setBackground(new java.awt.Color(102, 102, 102));
        lblPass.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblPass.setForeground(new java.awt.Color(255, 255, 255));
        lblPass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPass.setText("Password :");
        add(lblPass);
        lblPass.setBounds(30, 270, 130, 20);

        lblUserName.setBackground(new java.awt.Color(102, 102, 102));
        lblUserName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblUserName.setForeground(new java.awt.Color(255, 255, 255));
        lblUserName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserName.setText("User name:");
        lblUserName.setOpaque(true);
        add(lblUserName);
        lblUserName.setBounds(30, 180, 140, 40);

        txtUser.setBackground(new java.awt.Color(102, 102, 102));
        txtUser.setForeground(new java.awt.Color(255, 255, 255));
        txtUser.setBorder(null);
        add(txtUser);
        txtUser.setBounds(180, 180, 300, 40);

        PswPass.setBackground(new java.awt.Color(102, 102, 102));
        PswPass.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        PswPass.setForeground(new java.awt.Color(255, 255, 255));
        PswPass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PswPass.setToolTipText("Password");
        PswPass.setBorder(null);
        PswPass.setDropMode(javax.swing.DropMode.INSERT);
        add(PswPass);
        PswPass.setBounds(170, 250, 310, 40);
        PswPass.getAccessibleContext().setAccessibleName("");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/adduser.png"))); // NOI18N
        add(jLabel3);
        jLabel3.setBounds(210, 20, 150, 140);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUserActionPerformed

        UserActivity userActivity = new UserActivity();
        userActivity.addUser(txtUser.getText(), PswPass.getText());
        txtUser.setText("");
        PswPass.setText("");
        JOptionPane.showMessageDialog(null, "SAVED");
        
    }//GEN-LAST:event_btnAddUserActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PswPass;
    private javax.swing.JButton btnAddUser;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
