/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.pim.view;

import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import ec.edu.espe.pim.controller.Inventory;
import ec.edu.espe.pim.model.Color;
import ec.edu.espe.pim.model.PairOfShoes;
import ec.edu.espe.pim.model.Tipo;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author S-Developers
 */

public class FrmInventory extends javax.swing.JFrame {

    private int search;

    /**
     * Creates new form FrmInventory
     */
    private final String ruta = System.getProperties().getProperty("user.dir");
    public FrmInventory() {
        initComponents();
        this.setTitle("PIM");
        this.setLocationRelativeTo(null);
        setLocationRelativeTo(null);
        File archivo = null;
        FileReader FileR = null;
        BufferedReader BufferedR = null;
        String tiposJson = "";
        String forsJson = "";
        
        ArrayList<Tipo> tipos = new ArrayList<>();
        ArrayList<Color> fors = new ArrayList<>();
        
        Gson gson = new Gson();
        try {
            archivo = new File(ruta + "//type.json");
            
            FileR = new FileReader(archivo);
            BufferedR = new BufferedReader(FileR);
            String line;
            
            DefaultComboBoxModel tiposComboBox = new DefaultComboBoxModel();
            while ((line = BufferedR.readLine()) != null) {
            
                tiposJson = tiposJson + line;
                
            }
            java.lang.reflect.Type tiposType = new TypeToken<ArrayList<Tipo>>() {}.getType();
            tipos = gson.fromJson(tiposJson, tiposType);

            for (Tipo tipo : tipos) {
                tiposComboBox.addElement(tipo.getDescription());
            }
            cmbType.setModel(tiposComboBox);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(btnDelete, e);
        } finally {
            try {
                if (null != FileR) {
                    FileR.close();
                }
            } catch (IOException e2) {
            }
            
        }
         try {
            archivo = new File(ruta + "//color.json");
            
            FileR = new FileReader(archivo);
            BufferedR = new BufferedReader(FileR);
            String line;
            
            DefaultComboBoxModel forsComboBox = new DefaultComboBoxModel();
            while ((line = BufferedR.readLine()) != null) {
            
                forsJson = forsJson + line;
                
            }
            java.lang.reflect.Type forsType = new TypeToken<ArrayList<Color>>() {}.getType();
            fors = gson.fromJson(forsJson,forsType);

            for (Color for1 : fors) {
                forsComboBox.addElement(for1.getDescription());
            }
            cmbColor.setModel(forsComboBox);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(btnDelete, e);
        } finally {
            try {
                if (null != FileR) {
                    FileR.close();
                }
            } catch (IOException e2) {
            }
    }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cmbType = new javax.swing.JComboBox<>();
        cmbColor = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtBrand = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtSize = new javax.swing.JTextField();
        spnStock = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        btnModify = new javax.swing.JButton();
        btnShowInventory = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnReturn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Cambria Math", 3, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 102, 255));
        jLabel5.setText("Inventario ");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 200, 30));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 190, 10));

        jLabel1.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("Código");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 255));
        jLabel2.setText("Marca");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        txtId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdKeyTyped(evt);
            }
        });
        jPanel2.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 130, -1));

        jLabel8.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 255));
        jLabel8.setText("Tipo");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, -1, -1));
        jPanel2.add(cmbType, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 110, -1));
        jPanel2.add(cmbColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 110, -1));

        jLabel9.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 255));
        jLabel9.setText("Color");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 50, 30));

        txtBrand.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBrandKeyTyped(evt);
            }
        });
        jPanel2.add(txtBrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 130, -1));

        txtPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPriceKeyTyped(evt);
            }
        });
        jPanel2.add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 130, -1));

        jLabel6.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 255));
        jLabel6.setText("Precio");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jLabel7.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 255));
        jLabel7.setText("Talla");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        txtSize.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSizeKeyTyped(evt);
            }
        });
        jPanel2.add(txtSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 30, -1));

        spnStock.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        jPanel2.add(spnStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 255));
        jLabel3.setText("Cantidad");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, -1, -1));

        btnModify.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espe/pim/images/modify.png"))); // NOI18N
        btnModify.setText("Modificar");
        btnModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyActionPerformed(evt);
            }
        });
        jPanel2.add(btnModify, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 120, -1));

        btnShowInventory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espe/pim/images/show.png"))); // NOI18N
        btnShowInventory.setText("Ver Inventario");
        btnShowInventory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnShowInventoryMouseClicked(evt);
            }
        });
        jPanel2.add(btnShowInventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, -1, 40));

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espe/pim/images/save.png"))); // NOI18N
        btnSave.setText("Guardar");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel2.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 120, 40));

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espe/pim/images/remove.png"))); // NOI18N
        btnDelete.setText("Borrar");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel2.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, 110, 40));

        btnReturn.setText("Regresar");
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });
        jPanel2.add(btnReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, 110, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        FrmMenuAdmin ad = new FrmMenuAdmin();
        ad.show();
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        FrmMenuAdmin ad = new FrmMenuAdmin();
        ad.show();
    }//GEN-LAST:event_formWindowClosing

    private void txtIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdKeyTyped
        char c = evt.getKeyChar();
        if(c<'0' || c>'9') evt.consume();
    }//GEN-LAST:event_txtIdKeyTyped

    private void txtBrandKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBrandKeyTyped
        char c = evt.getKeyChar();
        if((c<'a' || c>'z') && (c<'A') | c>'Z' && (c<'Ñ') && c !=KeyEvent.VK_SPACE)  evt.consume();
    }//GEN-LAST:event_txtBrandKeyTyped

    private void txtPriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPriceKeyTyped

    }//GEN-LAST:event_txtPriceKeyTyped

    private void txtSizeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSizeKeyTyped
        char c = evt.getKeyChar();
        if(c<'0' || c>'9') evt.consume();
    }//GEN-LAST:event_txtSizeKeyTyped

    private void btnModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyActionPerformed
        String id=txtId.getText();
        String brand=txtBrand.getText();
        String price=txtPrice.getText();
        String size=txtSize.getText();
        String shoeType=cmbType.getSelectedItem().toString();
        String color=cmbColor.getSelectedItem().toString();
        String stock = spnStock.getValue().toString();

        PairOfShoes a=new PairOfShoes(id,size,color,brand,price,shoeType,stock);

        txtId.setText("");
        txtBrand.setText("");
        txtPrice.setText("");
        txtSize.setText("");
        cmbType.setSelectedItem("");
        cmbColor.setSelectedItem("");
        int i= JOptionPane.showConfirmDialog(this,"Estas seguro que quieres modificar?");
        if ( i==0){
            JOptionPane.showMessageDialog(this,"La información a sido modificada");
        }
    }//GEN-LAST:event_btnModifyActionPerformed

    private void btnShowInventoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShowInventoryMouseClicked
        FrmData show=new FrmData();
        show.setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnShowInventoryMouseClicked

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        Inventory inventory = new Inventory();
        inventory.addProduct(Integer.valueOf(txtId.getText()),
            (Integer.valueOf(txtSize.getText())),
            (txtBrand.getText()),
            (cmbColor.getSelectedItem().toString()),
            (Float.valueOf(txtPrice.getText())),
            (cmbType.getSelectedItem().toString()),
            (Integer)spnStock.getValue());

        System.out.println((Integer.valueOf(txtId.getText())+
            (Integer.valueOf(txtSize.getText()))+
            (txtBrand.getText())+
            (cmbColor.getSelectedItem().toString())+
            (Float.valueOf(txtPrice.getText()))+
            (cmbType.getSelectedItem().toString())+
            (Integer)spnStock.getValue()));
    JOptionPane.showMessageDialog(this," Guardado...");
    txtId.setText("");
    txtBrand.setText("");
    txtPrice.setText("");
    txtSize.setText("");
    cmbType.setSelectedItem("");
    cmbColor.setSelectedItem("");

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        txtId.setText("");
        txtBrand.setText("");
        txtPrice.setText("");
        txtSize.setText("");
        cmbType.setSelectedItem("");
        cmbColor.setSelectedItem("");
        JOptionPane.showMessageDialog(this,"Estas seguro que quieres eliminar este producto?");
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        FrmMenuAdmin admin = new FrmMenuAdmin();
        admin.show();
        this.hide();
        this.setVisible(false);
    }//GEN-LAST:event_btnReturnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * Color details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmInventory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnModify;
    private javax.swing.JButton btnReturn;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnShowInventory;
    private javax.swing.JComboBox<String> cmbColor;
    private javax.swing.JComboBox<String> cmbType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner spnStock;
    private javax.swing.JTextField txtBrand;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtSize;
    // End of variables declaration//GEN-END:variables
}
