/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.pim.view;

import com.sun.awt.AWTUtilities;
import ec.edu.espe.pim.controller.SignIn;
import javax.swing.JOptionPane;
import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author S-Developers
 */
public class FrmMainLogin extends javax.swing.JFrame {

    int x, y;
    /**
     * Creates new form main
     */
    private final String ruta = System.getProperties().getProperty("user.dir");

    public FrmMainLogin() {
        this.setUndecorated(true);
        initComponents();
        AWTUtilities.setWindowOpaque(this, false);
        this.setLocationRelativeTo(null);
        this.jTxtUser.setFocusable(true);
    }
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("Resources/tacones.png"));

        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jUser1 = new javax.swing.JLabel();
        jTxtUser = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jUser = new javax.swing.JLabel();
        pswPass = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        jbtnLoging = new javax.swing.JButton();
        lblClose1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(240, 240, 240));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jUser1.setBackground(new java.awt.Color(0, 0, 0));
        jUser1.setFont(new java.awt.Font("Segoe Print", 3, 24)); // NOI18N
        jUser1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jUser1.setText("Nombre de Usuario");
        jPanel1.add(jUser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 240, 40));

        jTxtUser.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTxtUser.setBorder(null);
        jTxtUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtUserKeyTyped(evt);
            }
        });
        jPanel1.add(jTxtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 230, 40));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 230, 20));

        jUser.setFont(new java.awt.Font("Segoe Print", 3, 24)); // NOI18N
        jUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jUser.setText("Contraseña");
        jPanel1.add(jUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 140, 40));

        pswPass.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pswPass.setBorder(null);
        pswPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pswPassActionPerformed(evt);
            }
        });
        pswPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pswPassKeyTyped(evt);
            }
        });
        jPanel1.add(pswPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 230, 40));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 230, 10));

        jbtnLoging.setBackground(new java.awt.Color(102, 204, 255));
        jbtnLoging.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jbtnLoging.setText("Entrar");
        jbtnLoging.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnLogingMouseClicked(evt);
            }
        });
        jbtnLoging.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLogingActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnLoging, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, 100, 30));

        lblClose1.setBackground(new java.awt.Color(255, 255, 255));
        lblClose1.setFont(new java.awt.Font("Tahoma", 0, 23)); // NOI18N
        lblClose1.setForeground(new java.awt.Color(51, 51, 51));
        lblClose1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose1.setText("X");
        lblClose1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblClose1MouseClicked(evt);
            }
        });
        jPanel1.add(lblClose1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 20, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/zapato.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 290, 380));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtUserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtUserKeyTyped

    }//GEN-LAST:event_jTxtUserKeyTyped

    private void pswPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pswPassActionPerformed
    }//GEN-LAST:event_pswPassActionPerformed

    private void pswPassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pswPassKeyTyped
    }//GEN-LAST:event_pswPassKeyTyped

    private void jbtnLogingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnLogingMouseClicked
    }//GEN-LAST:event_jbtnLogingMouseClicked

    private void jbtnLogingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLogingActionPerformed

        FrmMenuAdmin frmMenuAdmin = new FrmMenuAdmin();
        FrmUserMenu frmMenuOption = new FrmUserMenu();
        SignIn sigIn = new SignIn();
        int flag;

        if ("Admin".equals(jTxtUser.getText()) && "shoePIM".equals(pswPass.getText())) {
            frmMenuAdmin.setVisible(true);
            dispose();
        } else {
            flag = sigIn.signInUser(jTxtUser.getText(), pswPass.getText());
            if (flag == 1) {
                this.setVisible(false);
                JOptionPane.showMessageDialog(null, "B I E N V E N I D O !!!");
                frmMenuOption.setVisible(true);
                dispose();
            } else if (flag == 2 || flag == 3) {
                JOptionPane.showMessageDialog(null, " USUARIO O CONTRASEÑA INCORRECTOS!!! ");
            } else {
                JOptionPane.showMessageDialog(null, "ERROR");
            }
        }

    }//GEN-LAST:event_jbtnLogingActionPerformed

    private void lblClose1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClose1MouseClicked

        System.exit(0);
    }//GEN-LAST:event_lblClose1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMainLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMainLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMainLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMainLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMainLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTxtUser;
    private javax.swing.JLabel jUser;
    private javax.swing.JLabel jUser1;
    private javax.swing.JButton jbtnLoging;
    private javax.swing.JLabel lblClose1;
    private javax.swing.JPasswordField pswPass;
    // End of variables declaration//GEN-END:variables
}
