/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.pim.view;

import ec.edu.espe.pim.controller.Inventory;
import ec.edu.espe.pim.controller.UserActivity;
import javax.swing.JOptionPane;

/**
 *
 * @author lesly
 */
public class PnlProduct extends javax.swing.JPanel {
    
    int idShoes;
    int stockShoes;
    
    /**
     * Creates new form Product
     */
    public PnlProduct() {
        initComponents();
    }
    
    
    public PnlProduct(int ID, String brand, String type,
            int size, String color, float price,int stocks){
        initComponents();
        this.idShoes = ID;
        this.stockShoes = stocks;
        this.id.setText(String.valueOf(ID));
        this.brand.setText(brand);
        this.ShoeType1.setText(type);
        this.size.setText(String.valueOf(size));
        this.color1.setText(color);
        this.price.setText("$" + String.valueOf(price));
        this.stock.setText(String.valueOf(stocks));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblID2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblID4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblBrand = new javax.swing.JLabel();
        lblShoeType = new javax.swing.JLabel();
        lblID3 = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        brand = new javax.swing.JLabel();
        size = new javax.swing.JLabel();
        lblSize = new javax.swing.JLabel();
        lblColor = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        btnBuy = new javax.swing.JButton();
        ShoeType1 = new javax.swing.JLabel();
        color1 = new javax.swing.JLabel();
        lblStock = new javax.swing.JLabel();
        stock = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setMaximumSize(new java.awt.Dimension(272, 165));
        setMinimumSize(new java.awt.Dimension(272, 165));
        setPreferredSize(new java.awt.Dimension(272, 165));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblID2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(lblID2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setMaximumSize(new java.awt.Dimension(272, 165));
        jPanel4.setMinimumSize(new java.awt.Dimension(272, 165));
        jPanel4.setPreferredSize(new java.awt.Dimension(272, 165));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblID4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel4.add(lblID4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setMaximumSize(new java.awt.Dimension(272, 165));
        jPanel1.setMinimumSize(new java.awt.Dimension(272, 165));
        jPanel1.setPreferredSize(new java.awt.Dimension(272, 165));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBrand.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        lblBrand.setForeground(new java.awt.Color(0, 51, 153));
        lblBrand.setText("Marca:");
        jPanel1.add(lblBrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        lblShoeType.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        lblShoeType.setForeground(new java.awt.Color(0, 51, 153));
        lblShoeType.setText("Tipo:");
        jPanel1.add(lblShoeType, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 30));

        lblID3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        lblID3.setForeground(new java.awt.Color(0, 51, 153));
        lblID3.setText("Codigo:");
        jPanel1.add(lblID3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        id.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        id.setText("ID:");
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, -1, -1));

        brand.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        brand.setText("BRAND:");
        jPanel1.add(brand, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        size.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        size.setText("size:");
        jPanel1.add(size, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, -1, -1));

        lblSize.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        lblSize.setForeground(new java.awt.Color(0, 51, 153));
        lblSize.setText("Talla:");
        jPanel1.add(lblSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, -1, 20));

        lblColor.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        lblColor.setForeground(new java.awt.Color(0, 51, 153));
        lblColor.setText("Color:");
        jPanel1.add(lblColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, 20));

        price.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        price.setForeground(new java.awt.Color(153, 0, 0));
        price.setText("$price");
        jPanel1.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 80, 20));

        btnBuy.setBackground(new java.awt.Color(0, 0, 51));
        btnBuy.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnBuy.setForeground(new java.awt.Color(255, 255, 255));
        btnBuy.setText("Buy");
        btnBuy.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 280, 30));

        ShoeType1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        ShoeType1.setText("ShoeType:");
        jPanel1.add(ShoeType1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        color1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        color1.setText("color:");
        jPanel1.add(color1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, 20));

        lblStock.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        lblStock.setForeground(new java.awt.Color(0, 51, 153));
        lblStock.setText("Cantidad:");
        jPanel1.add(lblStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, 30));

        stock.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        stock.setText("stock");
        jPanel1.add(stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, -1));

        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 160));

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 160));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyActionPerformed
        UserActivity activity = new UserActivity();
        Inventory inventoy = new Inventory();
        int newStock;
        int quanty;
        try{
            quanty = Integer.valueOf(JOptionPane.showInputDialog("Cuantós pares de zapatos desea comprar?"));
            if(! ( this.stockShoes >= quanty) ){
                JOptionPane.showMessageDialog(null, "Cantidad Insuficiente...","E R R O R",JOptionPane.ERROR_MESSAGE);
            }else{
                activity.addToCart(this.idShoes, quanty);
                inventoy.discount(inventoy.showProduct(), this.idShoes , quanty);
                newStock = stockShoes - quanty;
                this.stock.setText(String.valueOf( newStock ));
            }
        }catch (NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Ingrese solo números");
        }

        //new PnlBill().setVisible(true);
    }//GEN-LAST:event_btnBuyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ShoeType1;
    private javax.swing.JLabel brand;
    private javax.swing.JButton btnBuy;
    private javax.swing.JLabel color1;
    private javax.swing.JLabel id;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblBrand;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblID2;
    private javax.swing.JLabel lblID3;
    private javax.swing.JLabel lblID4;
    private javax.swing.JLabel lblShoeType;
    private javax.swing.JLabel lblSize;
    private javax.swing.JLabel lblStock;
    private javax.swing.JLabel price;
    private javax.swing.JLabel size;
    private javax.swing.JLabel stock;
    // End of variables declaration//GEN-END:variables
}
