/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.pim.view;

/**
 *
 * @author lesly
 */
public class PnlProduct extends javax.swing.JPanel {

    /**
     * Creates new form Product
     */
    public PnlProduct() {
        initComponents();
    }
    
    public PnlProduct(int ID, String brand, String type,
            int size, String color, float price){
        initComponents();
        this.id.setText(String.valueOf(ID));
        this.brand.setText(brand);
        this.ShoeType1.setText(type);
        this.size.setText(String.valueOf(size));
        this.color1.setText(color);
        this.price.setText(String.valueOf(price));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblID2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblBrand = new javax.swing.JLabel();
        lblShoeType = new javax.swing.JLabel();
        lblID3 = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        brand = new javax.swing.JLabel();
        size = new javax.swing.JLabel();
        lblSize = new javax.swing.JLabel();
        lblColor = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        ShoeType1 = new javax.swing.JLabel();
        color1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setMaximumSize(new java.awt.Dimension(276, 186));
        setMinimumSize(new java.awt.Dimension(276, 186));
        setPreferredSize(new java.awt.Dimension(276, 162));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblID2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(lblID2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setMaximumSize(new java.awt.Dimension(276, 186));
        jPanel1.setMinimumSize(new java.awt.Dimension(276, 186));
        jPanel1.setPreferredSize(new java.awt.Dimension(276, 162));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBrand.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        lblBrand.setForeground(new java.awt.Color(0, 51, 153));
        lblBrand.setText("BRAND:");
        jPanel1.add(lblBrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        lblShoeType.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        lblShoeType.setForeground(new java.awt.Color(0, 51, 153));
        lblShoeType.setText("Type:");
        jPanel1.add(lblShoeType, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        lblID3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        lblID3.setForeground(new java.awt.Color(0, 51, 153));
        lblID3.setText("ID:");
        jPanel1.add(lblID3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        id.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        id.setText("ID:");
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        brand.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        brand.setText("BRAND:");
        jPanel1.add(brand, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        size.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        size.setText("size:");
        jPanel1.add(size, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        lblSize.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        lblSize.setForeground(new java.awt.Color(0, 51, 153));
        lblSize.setText("Size: ");
        jPanel1.add(lblSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, 20));

        lblColor.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        lblColor.setForeground(new java.awt.Color(0, 51, 153));
        lblColor.setText("Color");
        jPanel1.add(lblColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        price.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        price.setForeground(new java.awt.Color(153, 0, 0));
        price.setText("price");
        jPanel1.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 0, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Buy");
        jButton1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 280, 30));

        ShoeType1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        ShoeType1.setText("ShoeType:");
        jPanel1.add(ShoeType1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        color1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        color1.setText("color:");
        jPanel1.add(color1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 200));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ShoeType1;
    private javax.swing.JLabel brand;
    private javax.swing.JLabel color1;
    private javax.swing.JLabel id;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblBrand;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblID2;
    private javax.swing.JLabel lblID3;
    private javax.swing.JLabel lblShoeType;
    private javax.swing.JLabel lblSize;
    private javax.swing.JLabel price;
    private javax.swing.JLabel size;
    // End of variables declaration//GEN-END:variables
}
