/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.pim.view;

import ec.edu.espe.pim.model.PairOfShoes;
import ec.edu.espe.pim.controller.Inventory;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.Insets;
import java.util.ArrayList;

/**
 *
 * @author S-Developers
 */
public class PnlSellProduct extends javax.swing.JPanel {

    /**
     * Creates new form FrmSellProduct
     */
    public PnlSellProduct() {
        initComponents();
        ChargeData();
        /*PRUEBA pi = new PRUEBA();
        pi.setSize(bodyPanel.getWidth(), bodyPanel.getHeight());
        pi.setLocation(5, 5);
        bodyPanel.removeAll();
        bodyPanel.add(pi);
        bodyPanel.revalidate();
        bodyPanel.repaint();*/
    }
    public final void ChargeData(){
        
        Inventory inventory = new Inventory();
        ArrayList<PairOfShoes> data = inventory.showProduct();
        //ArrayList<Panel> panel = new ArrayList<>();
        GridBagConstraints gbc = new GridBagConstraints();
        this.bodyPanel.setLayout(new GridBagLayout());
        int row = 0;
        int colum =0 ;
        
        for(PairOfShoes shoe : data){
            gbc.gridx = row;
            gbc.gridy = colum;
            gbc.gridwidth = 1;
            gbc.gridheight = 1;
            gbc.fill = GridBagConstraints.BOTH;
            gbc.anchor = GridBagConstraints.NORTHWEST;
            gbc.weightx= 1;
            gbc.weighty = 1;
            //gbc.insets = new Insets(10, 50, 50, 50);
            PnlProduct p = new PnlProduct(shoe.getId(),shoe.getBrand(), shoe.getShoeType() , shoe.getSize(), shoe.getColor(),shoe.getPrice());
            //p.set
            //p.setPreferredSize(new Dimension(276, 186));
            bodyPanel.add(p,gbc);
            row++;
            if(row % 3 ==0){ colum++;row=0;}
            
        }
        //this.bodyPanel.setSize(1050, 780);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnShop = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bodyPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1018, 548));
        setMinimumSize(new java.awt.Dimension(1018, 548));
        setPreferredSize(new java.awt.Dimension(1018, 548));
        setLayout(new java.awt.CardLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnShop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/cart.png"))); // NOI18N
        jPanel2.add(btnShop, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 20, 70, 70));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
        jScrollPane1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jScrollPane1.setMinimumSize(new java.awt.Dimension(890, 600));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(890, 800));

        bodyPanel.setBackground(new java.awt.Color(0, 0, 0));
        bodyPanel.setMaximumSize(new java.awt.Dimension(817, 650));
        bodyPanel.setMinimumSize(new java.awt.Dimension(817, 650));
        bodyPanel.setPreferredSize(new java.awt.Dimension(817, 650));
        bodyPanel.setLayout(new java.awt.GridBagLayout());
        jScrollPane1.setViewportView(bodyPanel);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 840, 500));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Logo.jpg"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, -1, -1));

        add(jPanel2, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JLabel btnShop;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
