/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.pim.view;

import ec.edu.espe.pim.controller.UserActivity;
import ec.edu.espe.pim.model.Users;
import ec.edu.espe.pim.utils.Encryption;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lesly
 */
public class PnlViewUser extends javax.swing.JPanel {

    /**
     * Creates new form ViewUser
     */
    public PnlViewUser() {
        initComponents();
        addData();
    }
    
    private void addData(){
        int filas = 0;
        DefaultTableModel model = (DefaultTableModel)this.tblUsers.getModel();
        UserActivity userActivity = new UserActivity();
        ArrayList<Users> listOfUsers = userActivity.readUsers();
        Encryption encryptPassword = new Encryption();
        
        for(Users user : listOfUsers){
            String[] fila = new String[2];
            fila[0] = user.getUser();
            fila[1] = encryptPassword.decrypt(user.getPassword());
            for(int i = 0;i<this.tblUsers.getColumnCount()-1;i++){
             model.setValueAt(fila[0] , filas, 0);
             model.setValueAt(fila[1], filas, 1);            
        }
           
            filas ++;
        }
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsers = new javax.swing.JTable();

        setLayout(new java.awt.CardLayout());

        tblUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Usuarios", "Contraseñas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblUsers);

        add(jScrollPane1, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUsers;
    // End of variables declaration//GEN-END:variables
}
