/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.pim.view;

import ec.edu.espe.pim.controller.UserActivity;
import ec.edu.espe.pim.model.User;
import ec.edu.espe.pim.utils.Encryption;
import java.util.ArrayList;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import sun.swing.table.DefaultTableCellHeaderRenderer;

/**
 *
 * @author S-Developers
 */
public class PnlViewUser extends javax.swing.JPanel {
   

    /**
     * Creates new form ViewUser
     */
    public PnlViewUser() {
        initComponents();
        //addData();
        ChargeInterface();
        ChargeData();
        
    }
    
    public void ChargeInterface(){
        DefaultTableModel model = (DefaultTableModel)this.tblUsers.getModel();
        
        String data[][]={};
        String column[]={"USERS","PASSWORD"};
        model=new DefaultTableModel(data,column);
        tblUsers.setModel(model);
        
        
        
    }
    
   
    
     public void ChargeData(){
        
        UserActivity userActivity = new UserActivity();
<<<<<<< HEAD
        ArrayList<User> data = userActivity.readUsers();
=======
        ArrayList<Users> data = userActivity.readUsers();
>>>>>>> c8345e324adb096f8f453d8ab8f4d83faed5950a
        DefaultTableModel model = (DefaultTableModel)this.tblUsers.getModel();
        Encryption encryptPassword = new Encryption();
        DefaultTableCellRenderer aling = new DefaultTableCellHeaderRenderer();
        aling.setHorizontalAlignment(SwingConstants.CENTER);
        
        int filas = 0;
            
        
<<<<<<< HEAD
        for(User shoe : data){
            Object [] fila = new Object [7];
            fila[0] = shoe.getUser();
            fila[1] = encryptPassword.decryptPassword( shoe.getPassword() );
=======
        for(Users shoe : data){
            Object [] fila = new Object [7];
            fila[0] = shoe.getUser();
            fila[1] = encryptPassword.decrypt( shoe.getPassword() );
>>>>>>> c8345e324adb096f8f453d8ab8f4d83faed5950a
            model.addRow(fila);
            for(int i = 0;i<this.tblUsers.getColumnCount()-1;i++){
             model.setValueAt(fila[0] , filas, 0);
             model.setValueAt(fila[1], filas, 1);
        }
            filas ++;    
        }
        tblUsers.getColumnModel().getColumn(0).setCellRenderer(aling);
        tblUsers.getColumnModel().getColumn(1).setCellRenderer(aling);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsers = new javax.swing.JTable();

        setLayout(new java.awt.CardLayout());

        tblUsers.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblUsers);

        add(jScrollPane1, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUsers;
    // End of variables declaration//GEN-END:variables
}
