/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.pim.view;

/**
 *
 * @author lesly
 */
public class Product extends javax.swing.JPanel {

    /**
     * Creates new form Product
     */
    public Product() {
        initComponents();
    }
    
    public Product(int ID, String brand, String type,
            int size, String color, float price){
        initComponents();
        this.id.setText(String.valueOf(ID));
        this.brand.setText(brand);
        this.ShoeType.setText(type);
        this.size.setText(String.valueOf(size));
        this.color.setText(color);
        this.price.setText(String.valueOf(price));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        image = new javax.swing.JLabel();
        lblBrand = new javax.swing.JLabel();
        lblShoeType = new javax.swing.JLabel();
        lblID2 = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        brand = new javax.swing.JLabel();
        ShoeType = new javax.swing.JLabel();
        lblSize = new javax.swing.JLabel();
        size = new javax.swing.JLabel();
        lblColor = new javax.swing.JLabel();
        color = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setMaximumSize(new java.awt.Dimension(276, 186));
        setMinimumSize(new java.awt.Dimension(276, 186));
        setPreferredSize(new java.awt.Dimension(276, 162));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        image.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 99, 90));

        lblBrand.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblBrand.setText("BRAND:");
        add(lblBrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        lblShoeType.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblShoeType.setText("Type:");
        add(lblShoeType, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, -1));

        lblID2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblID2.setText("ID:");
        add(lblID2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        id.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        id.setText("ID:");
        add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        brand.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        brand.setText("BRAND:");
        add(brand, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        ShoeType.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ShoeType.setText("ShoeType:");
        add(ShoeType, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, -1, -1));

        lblSize.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSize.setText("Size: ");
        add(lblSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, 20));

        size.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        size.setText("size");
        add(size, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, -1, -1));

        lblColor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblColor.setText("Color");
        add(lblColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));

        color.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        color.setText("color");
        add(color, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, -1));

        price.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        price.setText("price");
        add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 0, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Add to cart");
        jButton1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 129, 274, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ShoeType;
    private javax.swing.JLabel brand;
    private javax.swing.JLabel color;
    private javax.swing.JLabel id;
    private javax.swing.JLabel image;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblBrand;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblID2;
    private javax.swing.JLabel lblShoeType;
    private javax.swing.JLabel lblSize;
    private javax.swing.JLabel price;
    private javax.swing.JLabel size;
    // End of variables declaration//GEN-END:variables
}
