/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.pim.view;

import ec.edu.espe.pim.controller.Shoes;
import ec.edu.espe.pim.model.Inventory;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.Panel;
import java.util.ArrayList;
//import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lesly
 */
public final class PRUEBA extends javax.swing.JPanel {

    /**
     * Creates new form PRUEBA
     */
    public PRUEBA() {
        initComponents();
        ChargeData();
    }
    
   public void ChargeData(){
        
        Inventory inventory = new Inventory();
        ArrayList<Shoes> data = inventory.showProduct();
        //ArrayList<Panel> panel = new ArrayList<>();
        this.Scrol.setLayout(new GridBagLayout());
       
        for(Shoes shoe : data){
            Scrol.add(new Product(shoe.getId(),shoe.getBrand(), shoe.getShoeType() , shoe.getSize(), shoe.getColor(),shoe.getPrice()));
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Scrol = new javax.swing.JPanel();

        setMaximumSize(new java.awt.Dimension(1020, 550));
        setMinimumSize(new java.awt.Dimension(1020, 550));
        setPreferredSize(new java.awt.Dimension(1020, 550));
        setLayout(new java.awt.CardLayout());

        Scrol.setBackground(new java.awt.Color(153, 255, 255));
        add(Scrol, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Scrol;
    // End of variables declaration//GEN-END:variables
}
